### ISSUE TITLE
Confusion over how to report issues

### ISSUE THREAD

**Issue by robbieaverill** [zedtux/brewformulas.org#207]
Hi,

Today I found http://brewformulas.org/Chromedriver and ran the recommended installation instruction, which is now incorrect.

I followed the "Open new issue" link, and logged an issue explaining that the installation instructions are wrong - reply said [it is not part of homebrew, and to bring it up with you](https://github.com/Homebrew/homebrew-core/issues/26759#issuecomment-382238692).

1) How can I fix the installation instruction?
2) Can you please make it clearer how to report issues for this website? Given that it's not part of homebrew, the "Open new issue" is misleading, and I've ended up wasting the time of a homebrew maintainer pestering them about fixing examples on your website =)

Thanks!

**Comment by zedtux** [comment]
Thank you @robbieaverill for your issue.

First of all, I'm sorry about the confusion.

Please take into consideration that you've followed the installation instructions of an "Inactive" formula 
![chromedriver_ _brewformulas](https://user-images.githubusercontent.com/478564/38913551-a0adaec8-42db-11e8-9e99-f5eaa78f7bf9.png)

This means you shouldn't consider it. Inactive formulas are like deleted one, meaning in the past, when that formula has been created and indexed by brewformulas.org, the instruction was right.

Brewformulas.org is laking implementation of the Homebew cask and [an issue exists for that](https://github.com/zedtux/brewformulas.org/issues/54) which makes the formula being "Inactivated" when they switch it to a cask/tap.

> How can I fix the installation instruction?

You can open a pull request implementing what is described from the issue #54.

> Can you please make it clearer how to report issues for this website?

You can open a pull request with a suggestion. To me the button isn't misleading, so I guess I'm not the right candidate to work on that, but as you're confused, if you suggest something which works for me too, then I'll merge it with pleasure.

Aside note: If you look carefully at the homepage, there is the Jumbotron with the following:

```
Homebrew formulas index
The aim of this website is to provide an easy way to search for a Homebrew formula.
```

Did you come to brewformulas.org homepage and then search for Chromedriver, or did you came from a search engine to the formula's page?

**Comment by robbieaverill** [comment]
Thanks very much for the reply @zedtux!

>Did you come to brewformulas.org homepage and then search for Chromedriver, or did you came from a search engine to the formula's page?

I reached it through Google =)

I'd love to help out with #54 but I'm afraid I'm not familiar enough with Ruby to do so.

Thanks for responding!

**Comment by zedtux** [comment]
Well I should then add the brewformulas.org headline in the formula's show page.

> I'm not familiar enough with Ruby

Well it's then the right moment to start 👍
