### ISSUE TITLE
Footer 'Company 2013'

### ISSUE THREAD

**Issue by daconex** [zedtux/brewformulas.org#23]
In the footer, the 'Company' should be something like 'Homebrew Formulas' and it's not 2013 anymore. :)

![1fdd3098-98ab-40bf-af39-05e451a48e71](https://cloud.githubusercontent.com/assets/5752872/5930237/32e8efd0-a65b-11e4-841c-75c3aa43d505.PNG)

**Comment by zedtux** [comment]
this issue has been solved with the commit [666937e](https://github.com/zedtux/brewformulas.org/commit/666937e5370a79b9c09f56e1a8f955a0f7ffa394)
