### ISSUE TITLE
Search by Description

### ISSUE THREAD

**Issue by megadr01d** [zedtux/brewformulas.org#25]
The **Formula** search box only allows name of filename so if I search for `music` I only get GameMusicEmu and Libmusicbrainz. Why not search by any term present in the description so I can add a custom URL search to LaunchBar, eg. `http://brewformulas.org/search?utf8=✓&search%5Bterm%5D=*&commit=Search` (* = search term)?

**Comment by zedtux** [comment]
This a nice idea. Are you able to make a PR?

**Comment by megadr01d** [comment]
I'm afraid not, I'm not fluent in Ruby/Rails. I can't even find where the search box takes arguments in the code.

**Comment by zedtux** [comment]
Alright, thank you anyway for the request.

**Comment by megadr01d** [comment]
:+1:
