### ISSUE TITLE
list if recipes are in the boneyard

### ISSUE THREAD

**Issue by rdp** [zedtux/brewformulas.org#28]
Might be nice to note if a certain brew is in the "boneyard" or not.  For instance: http://brewformulas.org/Dsniff (either that, or allow use "comments" on each one).
Thanks!
-roger-

**Comment by zedtux** [comment]
@rdp what do you mean by "boneyard" ?

**Comment by rdp** [comment]
For instance, this formula "used" to exist but is not in the "graveyard"
(i.e. not supported) apparently:
https://github.com/Homebrew/homebrew/issues/27642

**Comment by rdp** [comment]
Nothing new that I've run into...

**Comment by zedtux** [comment]
What's next then?

Are you able to make me understanding the concept of boneyard and graveyard, or do we close this ticket?

**Comment by rdp** [comment]
feel free to close, I haven't run into this problem in awhile at least...

**Comment by zedtux** [comment]
Okay, thank you @rdp, feel free to reopen this ticket in the case you have this again.
