### ISSUE TITLE
home page on pkg-config is wrong; can't figure out how to fix it

### ISSUE THREAD

**Issue by cswarth** [zedtux/brewformulas.org#49]
I wish I could offer a PR to fix this but I can't figure out where this bad info is coming from.
Is the homepage link coming directly from the brew formula?  If so I apologize for wasting your time.

The [pkg-config formula](http://brewformulas.org/Pkg-config) has a bad link for the homepage.

**Homepage** https://wiki.freedesktop.org/www/Software/pkg-config/
should be something like
**Homepage** https://www.freedesktop.org/wiki/Software/pkg-config/

Looks like freedesktop.org reorganized their site without forwarding.

**Comment by zedtux** [comment]
Thank you @cswarth for reporting this.

The homepage is coming from the formula, as you guessed. You need to update [that file](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pkg-config.rb) and make a PR.
