### ISSUE TITLE
Version of IPFS formula is Unavailable

### ISSUE THREAD

**Issue by fzzr-** [zedtux/brewformulas.org#50]
[brewformulas.org/ipfs](http://brewformulas.org/ipfs)
![screen shot 2016-04-12 at 20 21 34](https://cloud.githubusercontent.com/assets/888526/14469198/9227cf62-00f4-11e6-8535-e66614b2212b.png)

But in the ([formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ipfs.rb#L7)) all is OK.

**Comment by zedtux** [comment]
The offending method is [`Homebrew::Tools.extract_attributes`](https://github.com/zedtux/brewformulas.org/blob/master/app/models/homebrew/tools.rb#L24) which expects to find a `version` element but it seems now it's an `url` element with arguments to parse.

A new scenario needs to added to the [features/look_at_a_formula.feature](https://github.com/zedtux/brewformulas.org/blob/master/features/look_at_a_formula.feature) file.

**Comment by zedtux** [comment]
Based on what I can see, the version is fetched from the formula URL, and the `version` method is used only when Homebrew fails at it.

I will then do the same and see.

**Comment by zedtux** [comment]
Here is regular expression to extract the version from the URL for the majority of the formulas: `(\d[\d\.\_]+\w?)(?:\.|-src|rc\d+)[\w\.]+$`.

I will also implement the case where the is a `tag` key given to `url`.
