### ISSUE TITLE
Request for results pagination feature on the formulas list view

### ISSUE THREAD

**Issue by fnouama** [zedtux/brewformulas.org#53]
This will strongly improve the UX of this web site

**Comment by zedtux** [comment]
Can you please better explain your request @fnouama ?

**Comment by fnouama** [comment]
@zedtux it will be easier to navigate your web site if the `formulas grid` was providing a tool bar with pagination and navigation (arrows) buttons

**Comment by zedtux** [comment]
Well this bar was here in the very first version and we migrated to the infinite scroll.

Why would it be easier to have this bar instead?

**Comment by zedtux** [comment]
In the new version (2.0), there is no more a page with all the formula, so no need to a pagination, problem solved 😉
