### ISSUE TITLE
qt5 webkit

### ISSUE THREAD

**Issue by u007** [zedtux/brewformulas.org#55]
hi,

im not sure if this is the place to report issue,
latest brew install qt5, does not seems to allow me to install capybara-webkit,
throwing
Project ERROR: Unknown module(s) in QT: webkitwidgets

ive tried all qt5 and qt55,
gem uninstall capybara-webkit (all)
brew linkapps qt5
brew link --force qt5

and run bundle
even tried QMAKE=/usr/local/Cellar... bundle install 
still fails

osx 10.11.5
ruby 1.9.3
gem 2.6.6

**Comment by zedtux** [comment]
Hello @u007,

This repository is only relating to the brewformulas.org website. Please open your issue in the [Homebrew github repo])(https://github.com/Homebrew/homebrew-core)
