### ISSUE TITLE
terraform from brew fails to read private certs

### ISSUE THREAD

**Issue by zapman449** [zedtux/brewformulas.org#56]
Steps to reproduce:
`brew install terraform`
terraform remote state against a backend with a private certificate.

Expected results:
Process would work normally if I've brought the cert into my cert keychain

Observed results:
Process fails with cert validation.

Workaround:
Compile terraform from source on OS X directly, rather than cross-compiling, or downloading from Terraform.io

**Comment by zedtux** [comment]
Sorry, brewformulas.org is just a list of formulae. You have to open your issue in the [Homebrew repository](https://github.com/Homebrew/homebrew-core).
