### ISSUE TITLE
Provide link to actual formula

### ISSUE THREAD

**Issue by cpcallen** [zedtux/brewformulas.org#59]
The Homebrew homepage says "homebrew formulae are simple Ruby scripts", and when I saw some [instructions providing an extra command line option to one of them](http://www.golangbootcamp.com/book/get_setup) I thought I'd look at the script to see what that option did before installing.

Unfortunately, contrary to the brew docs, `brew edit <packagename>` won't work for formulas that aren't already installed, so I did a search for `brew formula <packagename>`, which took me to your site.

Unfortunately, despite being named "Homebrew formulas", I can't find any way to *actually see the formula* for the package in question.  Please provide a way of seeing the formula!

**Comment by zedtux** [comment]
It's a good idea.

**Comment by Haroenv** [comment]
the link is https://github.com/Homebrew/homebrew-core/tree/master/Formula/{{formula}}.rb for core formulae

**Comment by timotheecour** [comment]
@cpcallen 
I recently added commandline functionality for `brew formula <packagename>` see: 

https://github.com/Homebrew/brew/commit/7281cfaf63e45f8e4e46340d724926d0adbd7ccc
https://github.com/Homebrew/brew/pull/1972

**Comment by zedtux** [comment]
@timotheecour this repository is for the web application brewformulas.org, not the command line.

Users are using the web in this context, not the command line, therefor I'm sorry but I don't see the point of the your comment.

**Comment by cpcallen** [comment]
@zedtux: I mentioned in my original report that I came to brewformulas.org after being unable to do something on the command line.  @timotheecour's comment was useful (at least to me) because now I know that the thing I originally wanted to do can be done from the command line.  Thanks Timothee, for adding this feature, and mentioning you'd done so.

I shall enjoy quickly reading formulae from the command line today AND look forward to doing so via brewformulas.org in due course!

**Comment by eexit** [comment]
Can't believe this feature is missing... When I look for a formula information, I also want to be able to see the source code of the formula.

Please add this—so wanted—link.
Thanks!

**Comment by zedtux** [comment]
This is now implemented in the new version, I hope to deploy it to prod during this week or the next week.
