### ISSUE TITLE
kibana 5.2.0 formula is incorrect

### ISSUE THREAD

**Issue by salvob41** [zedtux/brewformulas.org#62]
Kibana is now at its 5.2.0 version.
Even if `homebrew` after a `brew update/brew upgrade` command says that the kibana package is upgraded to 5.2.0 it is actually still at its 5.0.0 version as shown in [kibana formula link](http://brewformulas.org/Kibana).

**Comment by zedtux** [comment]
Hey @salvob41, thank you for your issue but this repository is only about the brewformulas.org website. Please open it in the Homebrew repository.

**Comment by salvob41** [comment]
In the link though ( http://brewformulas.org/Kibana) it says version `5.0.0-alpha3` while it is actually its `5.2.0` version
