### ISSUE TITLE
Description field should be parsed from `brew info X`, not extracted automatically from X homepage

### ISSUE THREAD

**Issue by timotheecour** [zedtux/brewformulas.org#63]
@zedtux
Description field should be parsed from `brew info X`, not extracted automatically from X homepage

case in point:

http://brewformulas.org/Ldc

shows

```
Description

LDC is an entirely community-driven effort, so all contributions are warmly welcomed. The easiest way to help with development is to write high-quality bug reports for any issues you run into. For a quick guide on what a useful report should contain, please see Reporting LDC issues.

Extracted automatically from Ldc homepage
```

which is a poor description compared to what one would get from `brew info ldc` which is:
```
ldc: stable 1.1.0, HEAD
Portable D programming language compiler
https://wiki.dlang.org/LDC
...
```

**Comment by zedtux** [comment]
The entire goal of brewformulas.org is to provide an automatic description, from the project's web page, which are better than the on given from the command line ("better" here means the command line tool is showing a very short sentence, while when fetching from the homepage it is better described and made by the project's author in general).

I admit the description aren't all the time nice, but it means opening a ticket to improve the way the descriptions are fetched, not to completely trash the way it fetches the descriptions.

I will not parse the `brew` command line output.
