### ISSUE TITLE
comparison with http://braumeister.org?

### ISSUE THREAD

**Issue by timotheecour** [zedtux/brewformulas.org#64]
I don't see any mention of http://braumeister.org so curious whether there's been some thought on feature differences vs that.
eg: http://braumeister.org/formula/ldc

**Comment by zedtux** [comment]
This project has not been made to fight with braumeister.org, but to provide another way to do the same thing. It could be that the result is better in certain cases on braumeister.org, and that's nice for braumeister.org, but I don't care.

Brewformulas.org needs more contribution from me or others, that's all. :)
