### ISSUE TITLE
Documentation about how descriptions are built

### ISSUE THREAD

**Issue by Yann-R** [zedtux/brewformulas.org#67]
Hello,

Just a few questions about descriptions sources in brewformulas.org.

brewformulas.org is a very nice place, pionner for instance in the aim of supplying descriptions for brew formulae at a time where they were not available in brew itself via `brew desc`.

Meantime, brew included its own searchable descriptions in formulae, but it appears to the user of brewformulas.org that those descriptions differ from the ones displayed by brewformulas.org.

I guess that, before and even now, descriptions available on brewformulas.org are built from the home web page of the software (automatically and maybe sometimes manually). Aren't they never extracted from the desc field in the formulae?

Thank you for any piece of information as answer.

P.S. Maybe this kind of explanation telling where the descriptions come from would be of great interest on the page describing brewformulas.org (https://github.com/zedtux/brewformulas.org) that just tells "Brewformulas.org is a website to easily search and discover Homebrew formulas."

**Comment by zedtux** [comment]
> I guess that, before and even now, descriptions available on brewformulas.org are built from the home web page of the software (automatically and maybe sometimes manually).

All description are extracted automatically. There's no manual way to write a description (there's even no form to do that :p)

It is true we could add the description from `brew desc` when there's no way to fetches automatically the description.
The information from where come from the description is shown the formula page, and could show "Extract from brew desc" when it come from that.

**Comment by zedtux** [comment]
@Yann-R please have a look at https://github.com/zedtux/brewformulas.org/wiki/Fix-or-add-description-fetching-strategy

**Comment by Yann-R** [comment]
Yes, thank you very much for this link, this is exactly the kind of explanation / reminder that interested my curiosity! :-)

> The information from where come from the description is shown the formula page

Yes, but you are speaking here of the content a user can see on http://brewformulas.org/
What I suggested in my first post was to add such kind of precision on the project page (https://github.com/zedtux/brewformulas.org) so as to let the user more easily understand what this software is supposed to do, and how.

For instance, using your useful link to the wiki above, you could simply rewrite the one-line description:

> Brewformulas.org is a website to easily search and discover Homebrew formulas.

into:

> Brewformulas.org is a website to easily search and discover Homebrew formulas. Their descriptions are automatically extracted [with different strategies](https://github.com/zedtux/brewformulas.org/wiki/Fix-or-add-description-fetching-strategy).

**Comment by zedtux** [comment]
@Yann-R I absolutely agree with you, please update the `README.md` file directly instead of posting a comment ;)

**Comment by zedtux** [comment]
I did the update in the new version.
