### ISSUE TITLE
android-platform-tools is now in cask

### ISSUE THREAD

**Issue by sbwoodside** [zedtux/brewformulas.org#75]
http://brewformulas.org/android-platform-tool is out of date.

See: https://github.com/Homebrew/homebrew-core/issues/11656

**Comment by zedtux** [comment]
Thank you @sbwoodside for your issue. Can you please confirm that your request relates to #54 ?

**Comment by sbwoodside** [comment]
The issue is that android-platform-tool has been moved to 

```
brew cask install android-platform-tools
```

(Note also that there's a plural on "tools")

**Comment by zedtux** [comment]
So I confirm this issue is the same as #54 so I close this one.
