### ISSUE TITLE
unable to report a formula as broken

### ISSUE THREAD

**Issue by ssbarnea** [zedtux/brewformulas.org#81]
The website seems nice and clean but it does not allow me to report a formula as broken and not even a link to a place where I can do that.

**Comment by zedtux** [comment]
What do you mean by reporting a formula as broken?

**Comment by ssbarnea** [comment]
As a brew user, sooner or later you will face a moment where "brew install foobar" either fails or succeeds installing a package that doesn't work (like giving a segmentation fault). 

At this moment it seems that there is almost no documentation on how to report a broken formula (or cask) and the brewformulas.org seems like the right place to help users. 

Ideally I would also add ability to upvote downvote formulas, but that would clearly be another ticket. 

PS. I think that there is lot to learn from how ansible galaxy works: https://galaxy.ansible.com/explore#/

**Comment by zedtux** [comment]
Thank you @ssbarnea for the clarification, I can consider your request.

So how would you see your request in the app?

 - A general link, always visible, pointing to the Homebrew github repository issues page
 - A link per formula, pointing to the Homebrew github repository new issue page with pre define title (I think it's possible to do so)
 - Something else?

**Comment by ssbarnea** [comment]
Indeed, a pre-populated new issue link would be very useful. Also it would be useful if we can display already existing tickets related to that formula.

**Comment by zedtux** [comment]
Oh you mean showing the open issues about a formula in the show page of the formula on brewformulas.org?

**Comment by zedtux** [comment]
Here is what I did in the new version of BrewFormulas:

![screen shot 2017-06-02 at 13 17 05](https://cloud.githubusercontent.com/assets/478564/26723642/cc86eed4-4795-11e7-909a-8056b3efab7b.png)

This opens a new tab to the URL :

![screen shot 2017-06-02 at 13 18 09](https://cloud.githubusercontent.com/assets/478564/26723678/f4bcb44c-4795-11e7-9117-26e21ecd2fb2.png)
